---
services:
  runescape-dragonwilds:
    image: ghcr.io/maximlibant/runescape-dragonwilds-server-docker:latest
    platform: linux/amd64
    restart: unless-stopped
    container_name: runescape-dragonwilds
    stop_grace_period: 30s
    ports:
      - 7777:7777/udp
    env_file:
      - .env
    volumes:
      - ./server-files:/home/steam/server-files
